### PR TITLE
add warning to CI

### PR DESCRIPTION
**Pull request by pleshevskiy**
DO NOT MERGE IT YET

### CODE REVIEW

**Comment by pleshevskiy** [comment]
Removed `allowed failure` for windows and macos. Disabled matrix cancellation on failure. Seems output better) @brxken128 You can merge now)

**Comment by brxken128** [comment]
> Removed `allowed failure` for windows and macos. Disabled matrix cancellation on failure. Seems output better) @brxken128 You can merge now)

Do we know *why* the tests are failing on Windows and MacOS? Is it something to do with different path handling between the platforms? I had some really, really odd issues with that before.

**Comment by pleshevskiy** [comment]
> Do we know why the tests are failing on Windows and MacOS?
only Windows.

> Is it something to do with different path handling between the platforms?
I think so)

**Comment by brxken128** [comment]
> I'll try to fix)

Good luck! It's probably something annoying - it might require platform-specific `#cfg[]` calls? Best thing I can think of :)

**Pull request merged**
