### PR TITLE
nix: add flake

### PR DESCRIPTION
**Pull request by pleshevskiy**
I've added a small flake for nix users

### CODE REVIEW

**Comment by brxken128** [comment]
I'm honestly not too involved with Nix, nor do I know too much about it, but this looks good. I'll just let Github's tests run and then merge.

Thanks for your PR!

**Comment by pleshevskiy** [comment]
@brxken128  now nix users can use the package as follows:

```sh
➜  ~ echo 'hello world' > text.txt
➜  ~ nix run github:brxken128/dexios -- encrypt text.txt test.enc
Password:
Password (for validation):
ℹ Using XChaCha20-Poly1305 for encryption
ℹ Encrypting text.txt (this may take a while)
✔ Successfully hashed your key [took 1.24s]
✔ Encryption successful! File saved as test.enc [took 0.00s]
```

**Comment by brxken128** [comment]
@pleshevskiy That is pretty cool! Thank you for the PR again, this seems like it was more than worth it.

**Comment by pleshevskiy** [comment]
@brxken128 Don't worry about it :) I've opened a new one https://github.com/brxken128/dexios/pull/89

**Pull request merged**
