### PR TITLE
ci: use matrix.os instead of runner.os

### PR DESCRIPTION
**Pull request by pleshevskiy**
Trying to fix actions

### CODE REVIEW

**Comment by brxken128** [comment]
Should I merge this? Seems to be fixed

**Comment by pleshevskiy** [comment]
@brxken128 You are was right about identation))) I hate yaml format) Fixed

**Comment by brxken128** [comment]
> @brxken128 You was right about identation))) I hate yaml format) Fixed

You and me both - it's a nightmare to figure out. On another note, great job with the cross-platform testing, all of the tests you've designed are extremely useful!

**Comment by pleshevskiy** [comment]
tests didn't pass on windows :thinking:

**Comment by brxken128** [comment]
> tests didn't pass on windows 🤔

I have a windows VM if anymore information could be relevant, just LMK :)

**Comment by pleshevskiy** [comment]
allowed failure for windows and macos tests

**Pull request merged**
