### PR TITLE
v8.0.0

### PR DESCRIPTION
**Pull request by brxken128**
There have been a lot of changes so far. It's not ready to be merged - but this is quite a large change.

Lots of things have been renamed, refactored, removed or even re-done to make things easier to follow.

Redundant functions have been removed entirely.

View the [roadmap](https://github.com/brxken128/dexios/projects/1) for specifics of this PR.

### CODE REVIEW

**Comment by brxken128** [comment]
@Rust-Galt I think this is ready to merge!

The [roadmap](https://github.com/brxken128/dexios/projects/1) has everything, I've cleaned up a lot of the code, removed some useless functions, refactored a fair amount.

Headers are now standardised with versioning, information about the mode/encryption algorithm.

Argon2 parameters aren't included in with the header, but they are linked with the header version itself. There are two bytes to denote the version (we can expand to 4 if required - I don't think it's necessary), so I think we have enough room for the future.

Hashing functions have been updated/implemented, the header functions have been updated to reflect the new header lengths - everything passes the tests with flying colours.

**Comment by Rust-Galt** [comment]
I'll have a quick look. I'm not that active this week. Everything I've read here sounds good. Just cloned and will have a look.

**Comment by Rust-Galt** [comment]
There is still a ` memory: bool,` floating around as a sort of mode switch. Everything else seem to be in enums and structs and is easier to understand.

**Comment by brxken128** [comment]
> There is still a ` memory: bool,` floating around as a sort of mode switch. Everything else seem to be in enums and structs and is easier to understand. in pack.rs

I can't see that anywhere - searching can't even find a reference to `memory` in `pack.rs`

> `file.is_dir();`

Good call, I've made that change - not a clue why I didn't think of that sooner.

**Comment by brxken128** [comment]
Having them as `fs` paths could work, it'd put more code in either `main.rs` or `parameters.rs` (like a `path_from_str` kinda function).

So far I've only tested the large Linux distributions, and FreeBSD13/14 - neither of them had issues.

I'll get to implementing that now actually, and then I think v8.0.0 is ready for publishing.

Thank you! :)

**Pull request merged**
