### PR TITLE
cli/pack: add possibility to pack many files

### PR DESCRIPTION
**Pull request by pleshevskiy**
Some improvement from me... I currently have the following makefile:

```
pack:
	$(MAKE) DEXIOS_KEY=$$(pass show dexios/business_documents) pack-unchecked

pack-unchecked:
	dexios -py companies companies.enc
	dexios -py my_contracts my_contracts.enc
	dexios -py my_courses my_courses.enc
	dexios -py nalog nalog.enc
	dexios -py assets assets.enc

unpack:
	$(MAKE) DEXIOS_KEY=$$(pass show dexios/business_documents) unpack-unchecked

unpack-unchecked:
	dexios -uy companies.enc .
	dexios -uy my_contracts.enc .
	dexios -uy my_courses.enc .
	dexios -uy nalog.enc .
	dexios -uy assets.enc .
```

these changes allow me to make things easier!

```
pack:
	pass show dexios/business_documents | dexios -pyk - companies my_contracts my_courses nalog assets all.enc

unpack:
	pass show dexios/business_documents | dexios -uyk - all.enc .
```

### CODE REVIEW

**Comment by pleshevskiy** [comment]
@brxken128 the tests are down... Cannot reproduce the error locally

**Comment by pleshevskiy** [comment]
Clap is confused and can't define boundaries. The only solution is to swap `input` and `output` params. And we can now use the pattern...

```
dexios pack -y flake.enc flake.*
```

**Comment by pleshevskiy** [comment]
Maybe there is another solution, but I have not found it.

**Comment by pleshevskiy** [comment]
@brxken128 I've tried both 
image

**Comment by pleshevskiy** [comment]
nope 
image

**Comment by brxken128** [comment]
> We could instead require explicit marking of the output file, with `-o` (and if none is set, we append the extension `.dx` to the end). I originally planned to do this in order to support encrypting multiple files at once (individually, not packed), but got annoyed with the clunkiness of the decryption function (if names were changed, we'd likely need to append an additional extension and stuff) - it just got messy.

We could just do this for only pack, for now at least. Require a manually specified output file, and if none is set, just default to a random word, some numbers and `.dx`. It will then be able to treat all lose text as input file names.

I don't think swapping input/output files around is a good solution, and if we can't find an alternative we could always open an issue upstream - I'm not too sure this is an issue with clap, and it may just be our usage.

**Comment by pleshevskiy** [comment]
I'll try to reproduce it with smaller parameters... I will create a separate repository. At least I could ask a question in clap

**Comment by brxken128** [comment]
> I'll try to reproduce it with smaller parameters... I will create a separate repository. At least I could ask a question in clap

That works also, good luck my friend!

p.s. I should be back and writing code tomorrow - my NAS boot SSD failed due to the heatwave (I assume it's because of the heatwave), and I'm in the process of reconfiguring it.

**Comment by pleshevskiy** [comment]
@brxken128 I've created a related issue https://github.com/clap-rs/clap/issues/3959

**Comment by brxken128** [comment]
> @brxken128 I've created a related issue [clap-rs/clap#3959](https://github.com/clap-rs/clap/issues/3959)

Looks good! Hopefully we can get to the bottom of this :)

**Pull request closed without merging**
