### PR TITLE
deps: add rpassword instead of termion

### PR DESCRIPTION
**Pull request by pleshevskiy**

### CODE REVIEW

**Comment by pleshevskiy** [comment]
I would upgrade to rpassword=7.0, but it crashes on that :thinking:

**Comment by brxken128** [comment]
> I would upgrade to rpassword=7.0, but `cargo` crashes on that 🤔

We'd honestly need `rpassword` at v7.0.0 or above - I don't feel comfortable adding it otherwise. Older versions pull in `serde` no matter what, as their features regarding `serde` were completely broken before 7.0.0. Dexios originally used `rpassword`, but due to this issue I replaced it for termion.

It's quite odd that `cargo` crashes on that, what's the specific error?

I'd love to move back to `rpassword`, because this means non-Unix users can have hidden password entry.

**Comment by pleshevskiy** [comment]
image

**Comment by pleshevskiy** [comment]
I figured out what's going on! I'm going to create an issue.

**Comment by pleshevskiy** [comment]
Updating Rust to 1.62 helped) And I almost created MR to remove the `dep:` prefix in the feature. Again I missed when they became stable.

**Comment by brxken128** [comment]
> Updating Rust to 1.62 helped) And I almost created MR to remove the `dep:` prefix in the feature. Again I missed when they became stable.

I don't mind raising our MSRV for this, I assume most people will be using it also so I don't think it'll be an issue there.

**Comment by pleshevskiy** [comment]
Are we going to merge this MR?

**Comment by brxken128** [comment]
> Are we going to merge this MR?

Yes :)

**Pull request merged**
