### PR TITLE
header: implement v5 headers

### PR DESCRIPTION
**Pull request by brxken128**
This is nowhere near done, at all.

I'm going to mark it as a draft for now - there's a **lot** to do. I need to:

* Read the actual information itself from the header
* Ensure that it can be done in a backwards-compatible manner
* Handle serialization of the headers (and AAD creation)
* Update the CLI app's functions (most notably the change password one)
* Probably some more

There are a lot of things needed for this to work correctly - hopefully it's not too bad.

### CODE REVIEW

**Comment by brxken128** [comment]
> To make everything work as expected at the end I can write tests)

That works for me :)

Having a quick break and then going to get back to it.

**Comment by brxken128** [comment]
As of my latest push, here's a rough outline of things I need to do before I'm happy with V5:

* Serializing. This includes the first 32 bytes of the header, and every possible keyslot with the correct padding. For every absent keyslot, it **needs** to write 96 empty bytes in it's place. The total length should be 416 bytes, and the reasoning behind this is detailed in #90.
* Creating AAD (this will just be version/mode/algorithm/nonce
* Reworking the CLI app to adhere to the new formats
    * This will probably include the main encrypt/decrypt functions also, as they'll need to loop through the returned `Vec<Keyslot>` and *attempt* to decrypt the master key with the user-provided key. If there are no matches, reject the user's key as it is incorrect.
    * We'll also need to rework key changing functionality almost fully
    * Ensure that header stripping/restoring/etc is in working order, with the correct length. This is vital and will be catastrophic if there's any undefined behaviour.

**Comment by brxken128** [comment]
a642c74d4585662182e7dbfbfdc2db132e450f58 seems to have overwritten the recent changes in the master branch. I'll try to fix this lol

**Comment by brxken128** [comment]
@pleshevskiy I've made some progress!

V5 headers work. I haven't tested it with multiple keys yet, as I need to add functionality for that within the header functions. I should also add support for argon2id, via `-a`.

It successfully encrypts, creates the AAD, deserializes and decrypts without a hitch.

**Comment by brxken128** [comment]
For some reason, V5 headers only work with XChaCha20-Poly1305. I feel as though I mistyped something regarding the nonce length somewhere (probably for header deserialization), but I can't quite find where. I'll take a look into it later on.

**Comment by pleshevskiy** [comment]
> https://github.com/brxken128/dexios/pull/111/commits/a642c74d4585662182e7dbfbfdc2db132e450f58 seems to have overwritten the recent changes in the master branch. I'll try to fix this lol
> 
> It went terribly wrong, and I blame that on my inexperience with git. Luckily I was able to find a local copy of header.rs, the file which contained most of this PR's work.

just use following commands to prevent common problems :)
```
# for example your branch is `v5`
git add .
git stash
git checkout master
git pull origin master
git checkout v5
git rebase master
# fix conflicts, and use `git rebase --continue`
git stash pop
```
all done. Your branch is rebased successfully :)

**Comment by pleshevskiy** [comment]
I'm sorry I'm trying to get a job as a Rust developer) I don't have time to do dexios yet)

**Comment by brxken128** [comment]
> > [a642c74](https://github.com/brxken128/dexios/commit/a642c74d4585662182e7dbfbfdc2db132e450f58) seems to have overwritten the recent changes in the master branch. I'll try to fix this lol
> > It went terribly wrong, and I blame that on my inexperience with git. Luckily I was able to find a local copy of header.rs, the file which contained most of this PR's work.
> 
> just use following commands to prevent common problems :)
> 
> ```
> # for example your branch is `v5`
> git add .
> git stash
> git checkout master
> git pull origin master
> git checkout v5
> git rebase master
> # fix conflicts, and use `git rebase --continue`
> git stash pop
> ```
> 
> all done. Your branch is rebased successfully :)

That's what I tried, and it just went downhill from there sadly. Thankfully I had the work backed up, otherwise that could've been annoying lol

**Comment by brxken128** [comment]
in

> I'm sorry I'm trying to get a job as a Rust developer) I don't have time to do dexios yet)

Not an issue, good luck my friend :)

**Comment by brxken128** [comment]
The changes in 5c7cf85352b970a46ed31d7885bcc03c4832d187 were made in order to separate the key functions from the header ones, but also in order to update the command syntax slightly.

I think `dexios key change` is worlds better than `dexios header update-key`.

I also plan to add a `dexios key add` function, which will be limited to V5+ headers and will only be available if < 4 keyslots are filled (as that is the hard limit within the standard).

**Comment by brxken128** [comment]
This is getting close to being finalised enough - I don't want to make too many changes, or else the merge conflicts will be a nightmare. `key add` functionality needs to be added, and `key change` functionality needs support for V5 headers, but aside from that things are pretty much done. I'll get to work on these in another PR.

**Pull request merged**
